[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scanpy-dgscrna"
version = "0.1.0"
description = "A scanpy extension for automated cell type annotation using density scoring and deep learning"
readme = "README.md"
authors = [
    {name = "DGscRNA Team", email = "your.email@example.com"},
]
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
requires-python = ">=3.8"
dependencies = [
    "scanpy>=1.9.0",
    "pandas>=1.3.0",
    "numpy>=1.20.0",
    "torch>=1.10.0",
    "torchmetrics>=0.6.0",
    "scikit-learn>=1.0.0",
    "matplotlib>=3.5.0",
    "seaborn>=0.11.0",
    "openpyxl>=3.0.0",
    "numba>=0.56.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=6.0",
    "pytest-cov",
    "black",
    "isort",
    "flake8",
]
plotting = [
    "plotly>=5.0.0",
]
all = [
    "scanpy-dgscrna[dev,plotting]"
]

[project.urls]
Homepage = "https://github.com/yourusername/scanpy-dgscrna"
Repository = "https://github.com/yourusername/scanpy-dgscrna.git"
Documentation = "https://scanpy-dgscrna.readthedocs.io"

[tool.setuptools.packages.find]
include = ["scanpy_dgscrna*"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
multi_line_output = 3
