source_path <- Sys.getenv('PTC_SCORE_SOURCE')
parsed <- parse(source_path)
stopifnot(identical(parsed[[length(parsed)-1L]][[1]],as.name('if')))
for(expression in parsed[seq_len(length(parsed)-2L)]) eval(expression)
tasks <- fromJSON(file.path(base,'protocol/pooled_partition_tasks.json'),simplifyVector=FALSE)
t <- tasks[[task_id+1L]]
prep <- file.path(base,'prepared',t$group)
obj <- readRDS(file.path(prep,if(t$assay=='integrated')'CCA_PCA30.rds' else 'RNA_normalized.rds'))
gd <- file.path(base,'pooled',t$group,t$correction)
stopifnot(file.exists(file.path(gd,'GEOMETRY_COMPLETE')))
pd <- file.path(gd,paste0(t$space,'_',t$clusterer))
context <- t;context$dispatch_sha256 <- digest(file=Sys.getenv('PTC_PARTITION_SCORE'),algo='sha256')
score_one(obj,pd,t$assay,names(libraries),c('none','mean','0.5'),context)
cat('Pooled partition scoring complete',t$task_id,'\n')
