"""Re-score saved brain_GBM predictions only; no new Darmanis model is fitted."""
import json
import os
from pathlib import Path
from common import ROOT,OUT,require_slurm,sha,write_json,complete,utc
from legacy_brain_lineage import curated_lineage,panel_lineage

def run():
    require_slurm()
    import numpy as np
    import pandas as pd
    from sklearn.metrics import f1_score,precision_recall_fscore_support,confusion_matrix
    source=ROOT/'results/methods/all_predictions.csv'
    obs=ROOT/'results/gbm/run_pooled_obs.csv'
    d=pd.read_csv(source,keep_default_na=False).set_index('cell')
    g=pd.read_csv(obs,index_col=0,keep_default_na=False)
    assert len(d)==3589 and d.index.is_unique and set(d.index)==set(g.index)
    g=g.loc[d.index]
    assert np.array_equal(d.GT.map(curated_lineage),d.GT_lin)
    initial='CellMarkerBrain_pooled_leiden_none';final=initial+'_DL'
    assert final in g and np.array_equal(g[initial].map(panel_lineage),d.DGscRNA)
    dest=OUT/'legacy_coverage_audit';dest.mkdir(exist_ok=True)
    methods=['SingleR','scmap','CHETAH','CellTypist','LogisticRegression']
    predictions={m:d[m].map(curated_lineage).to_numpy(dtype=str) for m in methods}
    predictions['DG-scRNA historical Python terminal']=g[final].map(panel_lineage).to_numpy(dtype=str)
    predictions['Historical marker-only control']=d.DGscRNA.to_numpy(dtype=str)
    rows=[];perclass=[];native_rows=d[['test_donor','GT','GT_lin']].copy()
    for method,p in predictions.items():
        native_rows[method]=p
        for donor,mask in [('ALL',np.ones(len(d),dtype=bool))]+[(v,d.test_donor.eq(v).to_numpy()) for v in sorted(d.test_donor.unique())]:
            y=d.GT_lin.to_numpy(dtype=str)[mask];q=p[mask];called=~np.isin(q,['Other','Unknown','Undecided',''])
            labels=sorted(set(y));n=len(y)
            rows.append(dict(method=method,scope=donor,n_cells=n,n_called=int(called.sum()),coverage=float(called.mean()),
                macroF1_all_cells_present_classes=float(f1_score(y,q,labels=labels,average='macro',zero_division=0)),
                accuracy_all_cells=float((y==q).mean()),
                macroF1_among_called_legacy_definition=float(f1_score(y[called],q[called],average='macro',zero_division=0)) if called.any() else None,
                information='labelled training-donor references' if method in methods else 'historical marker-derived labels',
                final_annotation=method!='Historical marker-only control'))
            if donor=='ALL':
                precision,recall,f1,support=precision_recall_fscore_support(y,q,labels=labels,zero_division=0)
                for lab,pp,rr,ff,nn in zip(labels,precision,recall,f1,support):
                    perclass.append(dict(method=method,label=lab,precision=pp,recall=rr,F1=ff,n_true=int(nn)))
    table=pd.DataFrame(rows);table.to_csv(dest/'saved_predictions_full_denominator.csv',index=False)
    pd.DataFrame(perclass).to_csv(dest/'saved_predictions_per_class.csv',index=False)
    native_rows.to_csv(dest/'saved_evaluation_labels.csv.gz')
    table[table.scope=='ALL'].to_csv(dest/'summary.csv',index=False)
    note='''# Historical brain_GBM table: denominator and terminal-stage correction

This is an evaluation-only audit of saved predictions on 3,589 brain_GBM cells.
No new Darmanis fit, feature search or marker optimization was performed. These
results remain a separate historical dataset/label-scope example and are not
pooled with the new GSE274546 cohort or used to claim general superiority.

The old GBM_DOC2 table used only called cells, allowing methods with different
abstention rates to have different denominators. This audit scores every cell,
reports coverage, and retains called-only scores as explicitly conditional.
The existing brain lineage mapping is reproduced and its source hash recorded;
the broad mapping's biological limitations are not repaired by changing the denominator.

The old score_methods.py selected the column ending in pooled_leiden_none, which
is the initial marker column. Saved pooled_leiden_none_DL predictions exist and
are used for the terminal DG-scRNA row here. The original marker column is only
a separately named no-DL control. This historical Python/Leiden workflow differs
from the current native-R workflow and cannot establish the original R recipe's
performance. The saved _DL endpoint and generating use_deep_learning=True call
establish the requested output stage; a modern per-condition training-status
manifest was not generated by that historical driver, so actual trained/no-op
counts cannot be recovered from a column suffix alone.

Reference methods used labelled training donors, while the marker method did not.
The old numerical table and files are preserved; this audit supersedes their
denominator/stage interpretation without inventing new model outputs.
'''
    (dest/'AUDIT.md').write_text(note)
    write_json(dest/'manifest.json',dict(status='completed',evaluation_only=True,new_fits=0,n_cells=len(d),
        old_DG_table_selected_initial_marker_column=True,terminal_column=final,
        terminal_training_execution_status='Not recoverable from the historical CSV/driver alone; no training-count claim',
        sources={str(source):sha(source),str(obs):sha(obs),str(ROOT/'handoff/methods/score_methods.py'):sha(ROOT/'handoff/methods/score_methods.py'),
            str(ROOT/'handoff/gbm/run_pooled.py'):sha(ROOT/'handoff/gbm/run_pooled.py')},
        mapping_sha256=sha(Path(__file__).with_name('legacy_brain_lineage.py')),job=os.environ['SLURM_JOB_ID'],completed_at=utc()))
    complete(dest)

if __name__=='__main__':run()
